# docker-compose.yml

version: '3'
services:
  portal-support:
    image: portal-support:latest
    build:
      context: ./portal-support
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./portal-support:/app
    environment:
      - NODE_ENV=production

  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
