# .github/workflows/build-and-push.yml

name: Build and Push Docker Images
run-name: Build - ${{ github.ref_name }} - ${{ github.run_number }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push API Docker image
      run: |
        docker build -t ${{ secrets.ECR_API_REPO_URI }}:latest -f api/Dockerfile api/
        docker push ${{ secrets.ECR_API_REPO_URI }}:latest

    - name: Build and push Frontend Docker image
      run: |
        docker build -t ${{ secrets.ECR_FRONTEND_REPO_URI }}:latest -f patient-support/Dockerfile patient-support/
        docker push ${{ secrets.ECR_FRONTEND_REPO_URI }}:latest
